### PR TITLE
Simplify config generation

### PR DESCRIPTION
**Pull request by merijn**
The TODO comment in `JDQZPPConfig.cmake.in` mentions wanting to not explicitly listing all the libraries, with the standard generated config that's not necessary, using `find_package()` (for example, in i-emic) will just automatically add the paths and targets for jdqz_tools without needing to explicitly list them.

### CODE REVIEW

**Comment by Sbte** [comment]
How is this supposed to work? You don't define any of the required config variables like `JDQZPP_LIBRARIES`.

**Comment by Sbte** [comment]
Note that i-emic is not really using it properly. A more correct usage would be something like

```
find_package(JDQZPP QUIET)
if (${JDQZPP_FOUND})
  include_directories(${JDQZPP_INCLUDE_DIRS})
  target_link_libraries(target ${JDQZPP_LIBRARIES})
endif()
```

**Comment by merijn** [comment]
This PR follows the examples in the CMake documentation, it doesn't set any config variables no, because that's not necessary to use those variables. The targets file already correctly sets the include directories (via the library interface) so in the i-emic code we can simply do `target_link_libraries(target jdqz_tools)` and it "Just Works (TM)".

I just tagged the corresponding i-emic change, although if you prefer we can keep it as it is now.

**Comment by Sbte** [comment]
The current implementation also follows the CMake documentation, but probably an older version. Could you point me to the new documentation?

Also, both implementations still suffer from the same issue, which is there there is not one variable that contains all library targets. For this reason you still need something like a manually generated `JDQZPP_LIBRARIES` variable. In this case it is of course only one library, but for Trilinos or i-emic it's a giant list.

**Comment by merijn** [comment]
> Also, both implementations still suffer from the same issue, which is that there is not one variable that contains all library targets. For this reason you still need something like a manually generated JDQZPP_LIBRARIES variable.

Well, that's only really relevant if there's plans to add multiple libraries, no?

Anyway, this change isn't super important (although I'd say we should probably keep the INTERFACE installation of the header files so that specifying include directories in i-emic becomes redundant). It's just one (of many things) I tried before figuring out that #8 was the real problem I was having.

**Comment by merijn** [comment]
It just follows the setup in: https://cmake.org/cmake/help/v3.8/manual/cmake-packages.7.html#creating-a-package-configuration-file

**Comment by Sbte** [comment]
> > Also, both implementations still suffer from the same issue, which is that there is not one variable that contains all library targets. For this reason you still need something like a manually generated JDQZPP_LIBRARIES variable.
> 
> Well, that's only really relevant if there's plans to add multiple libraries, no?

Sure, but you'd have to look at the CMake files in this project to figure out the name of the library, since it's not just jdqzpp or something. It would also break in case there is a change in library names between versions, or if a new library is added. To fix these problems, however, there seems to be some consensus on the usage of `project_LIBRARIES` and `project_INCLUDE_DIRS` for every project, so I think that we should stick to that. At least we should use the same convention for all of our projects (so JDQZPP, I-EMIC, HYMLS, etc.).

**Pull request closed without merging**
